style: fix  the "Add new record" UI
teableio/teable pull request #916
Opened 2024-09-17 02:35 UTC by AliceLanniste

close #912

2024-09-18 03:46 UTC, Sky-FE requested changes
The conflict needs to be resolved.

2024-09-18 08:16 UTC, AliceLanniste commented
I have no write access to resolve

2024-09-18 08:24 UTC, tea-artist commented
Here's how to resolve merge conflicts using rebase:

1. Sync your fork with the main repository:

```bash
# Add upstream remote (if not already added)
git remote add upstream https://github.com/teableio/teable.git

# Fetch latest changes from upstream
git fetch upstream

# Switch to local develop branch
git checkout develop

# Merge upstream develop into local develop
git merge upstream/develop

# Push updates to your fork
git push origin develop
```

2. Update and rebase your feature branch:

```bash
# Switch to your feature branch
git checkout fix/UI

# Rebase onto develop
git rebase develop
```

3. If conflicts occur, Git will pause the rebase. Use `git status` to see conflicting files.

4. Open each conflicting file and manually resolve conflicts. Conflict areas are marked like this:

```
<<<<<<< HEAD (Current Change)
Your changes
=======
Changes from develop branch
>>>>>>> commit-hash (Incoming Change)
```

5. Edit the file, keep the changes you want, and remove conflict markers.

6. After resolving conflicts, stage the changes:

```bash
git add .
```

7. Continue the rebase:

```bash
git rebase --continue
```

8. Repeat steps 4-7 if more conflicts arise.

9. Once rebase is complete, force push to your remote branch:

```bash
git push -f origin fix/UI
```

10. Refresh your Pull Request page on GitHub. The conflicts should be resolved and ready for merging.

Note: Be cautious with `git push -f` as it overwrites remote branch history. Use it only on your personal branches, not shared ones.

If you encounter issues, use `git rebase --abort` to cancel the rebase and return to the initial state.

2024-09-19 11:45 UTC, Sky-FE approved these changes

2024-09-19 13:14 UTC, merged